### ISSUE TITLE
Example code in README.md is incorrect

### ISSUE THREAD

**Issue by jeroenkoknl** [binxio/cfn-postgresql-user-provider#1]
The example says:

```yaml
KongUser:
    Type: Custom::PostgreSQLUser
    DependsOn: KongPassword
    Properties:
      Name: kong
      PasswordParameterName: /postgres/kong/PGPASSWORD
      WithDatabase: true
      DeletionPolicy: Retain 
      Database:                   # the server to create the new user or database in
        Host: postgres
        Port: 5432
        Database: root
        User: root
        PasswordParameterName: /postgres/root/PGPASSWORD                # put your root password is in the parameter store
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxioio-cfn-postgresql-user-provider-vpc-${AppVPC}'
```

This doesn't validate against the JSON schema. It should be like:

```yaml
KongUser:
    Type: Custom::PostgreSQLUser
    DependsOn: KongPassword
    Properties:
      User: kong
      PasswordParameterName: /postgres/kong/PGPASSWORD
      WithDatabase: true
      DeletionPolicy: Retain 
      Database:                   # the server to create the new user or database in
        Host: postgres
        Port: 5432
        DBName: root
        User: root
        PasswordParameterName: /postgres/root/PGPASSWORD                # put your root password is in the parameter store
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxioio-cfn-postgresql-user-provider-vpc-${AppVPC}'
```

So `Name` should be `User` and `Database` should be `DBName`.
