### ISSUE TITLE
No module named 'Queue'

### ISSUE THREAD

**Issue by hufon** [binxio/cfn-postgresql-user-provider#5]
Hi,

I try to use your custom resources.
But when i try to execute my cloudformation :

```
  SonarQubeRDSUser:
    Type: Custom::PostgreSQLUser
    Properties:
      User: sonarqube
      PasswordParameterName: /sonarqube/RDSPGPASSWORD
      WithDatabase: true
      DeletionPolicy: Retain 
      Database:                   # the server to create the new user or database in
        Host: !Ref MainRDSHostName
        Port: 3306
        DBName: !Ref MainRDSDatabaseName
        User: !Ref MainRDSUsername
        PasswordParameterName: /gitlab/PGPASSWD                # put your root password is in the parameter store
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-postgresql-user-provider-${VPCId}'
```

Here is the cloudwatch logs i have :
```
15:25:04
Unable to import module 'postgresql_user_provider': No module named 'Queue'
```
